import { createBrowserRouter } from "react-router-dom";
import LandingPage from "@/src/pages/LandingPage";
import ProfilesPage from "@/src/pages/ProfilesPage";
import DashboardPage from "@/src/pages/DashboardPage";
import StatusPage from "@/src/pages/StatusPage";
import CapacityPage from "@/src/pages/CapacityPage";
import InventoryPage from "@/src/pages/InventoryPage";
import ShoppingPage from "@/src/pages/ShoppingPage";
import MealsPage from "@/src/pages/MealsPage";
import TasksPage from "@/src/pages/TasksPage";
import ToolsPage from "@/src/pages/ToolsPage";
import NotFoundPage from "@/src/pages/NotFoundPage";
import RecipesLibraryPage from "@/src/pages/recipes/RecipesLibraryPage";
import AdminHomePage from "@/src/pages/admin/AdminHomePage";
import AdminCatalogPage from "@/src/pages/admin/AdminCatalogPage";
import ProtectedRoute from "@/src/components/common/ProtectedRoute";
import AdminRoute from "@/src/components/common/AdminRoute";
import { ROUTES } from "@/src/constants/routes";
export const router = createBrowserRouter([{ path: ROUTES.landing, element: <LandingPage />, errorElement: <NotFoundPage /> }, { path: ROUTES.profiles, element: <ProtectedRoute><ProfilesPage /></ProtectedRoute> }, { path: ROUTES.dashboard, element: <ProtectedRoute><DashboardPage /></ProtectedRoute> }, { path: ROUTES.status, element: <ProtectedRoute><StatusPage /></ProtectedRoute> }, { path: ROUTES.capacity, element: <ProtectedRoute><CapacityPage /></ProtectedRoute> }, { path: ROUTES.inventory, element: <ProtectedRoute><InventoryPage /></ProtectedRoute> }, { path: ROUTES.shopping, element: <ProtectedRoute><ShoppingPage /></ProtectedRoute> }, { path: ROUTES.meals, element: <ProtectedRoute><MealsPage /></ProtectedRoute> }, { path: ROUTES.tasks, element: <ProtectedRoute><TasksPage /></ProtectedRoute> }, { path: ROUTES.tools, element: <ProtectedRoute><ToolsPage /></ProtectedRoute> }, { path: ROUTES.recipes, element: <ProtectedRoute><RecipesLibraryPage /></ProtectedRoute> }, { path: ROUTES.admin, element: <AdminRoute><AdminHomePage /></AdminRoute> }, { path: ROUTES.adminCatalog, element: <AdminRoute><AdminCatalogPage /></AdminRoute> }, { path: "*", element: <NotFoundPage /> }]);
